# Form implementation generated from reading ui file 'GenerateReportsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class GenerateReportsDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 291)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 220, 181, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_generate_pdf = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_generate_pdf.setGeometry(QtCore.QRect(10, 20, 381, 91))
        self.groupBox_generate_pdf.setCheckable(True)
        self.groupBox_generate_pdf.setObjectName("groupBox_generate_pdf")
        self.checkBox_explanation = QtWidgets.QCheckBox(parent=self.groupBox_generate_pdf)
        self.checkBox_explanation.setGeometry(QtCore.QRect(20, 30, 151, 31))
        self.checkBox_explanation.setChecked(False)
        self.checkBox_explanation.setObjectName("checkBox_explanation")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.groupBox_generate_pdf)
        self.checkBox_2.setGeometry(QtCore.QRect(200, 30, 161, 31))
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox.setGeometry(QtCore.QRect(30, 120, 261, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 150, 201, 31))
        self.checkBox_3.setObjectName("checkBox_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reports generation"))
        self.groupBox_generate_pdf.setTitle(_translate("Dialog", "Generate PDF Report"))
        self.checkBox_explanation.setText(_translate("Dialog", "Exclude Explanations"))
        self.checkBox_2.setText(_translate("Dialog", "Exclude Plots"))
        self.checkBox.setText(_translate("Dialog", "Export Raw Excel Data"))
        self.checkBox_3.setText(_translate("Dialog", "Export Raw CSV Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = GenerateReportsDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())