# Form implementation generated from reading ui file 'synchronyAnalysisDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class SynchronyAnalysisDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(841, 793)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(560, 700, 171, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.NoButton)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 711))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_dtw_method = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_dtw_method.setGeometry(QtCore.QRect(10, 190, 421, 241))
        self.groupBox_dtw_method.setCheckable(True)
        self.groupBox_dtw_method.setChecked(True)
        self.groupBox_dtw_method.setObjectName("groupBox_dtw_method")
        self.label = QtWidgets.QLabel(parent=self.groupBox_dtw_method)
        self.label.setGeometry(QtCore.QRect(10, 110, 151, 31))
        self.label.setObjectName("label")
        self.spinBox_dtw_radius = QtWidgets.QSpinBox(parent=self.groupBox_dtw_method)
        self.spinBox_dtw_radius.setGeometry(QtCore.QRect(230, 110, 51, 31))
        self.spinBox_dtw_radius.setMinimum(1)
        self.spinBox_dtw_radius.setMaximum(10)
        self.spinBox_dtw_radius.setObjectName("spinBox_dtw_radius")
        self.checkBox_dtw_vec_smoothing = QtWidgets.QCheckBox(parent=self.groupBox_dtw_method)
        self.checkBox_dtw_vec_smoothing.setGeometry(QtCore.QRect(10, 190, 191, 51))
        self.checkBox_dtw_vec_smoothing.setObjectName("checkBox_dtw_vec_smoothing")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_dtw_method)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 191, 31))
        self.label_2.setObjectName("label_2")
        self.spinBox_dtw_window_size = QtWidgets.QSpinBox(parent=self.groupBox_dtw_method)
        self.spinBox_dtw_window_size.setGeometry(QtCore.QRect(230, 150, 51, 31))
        self.spinBox_dtw_window_size.setMinimum(3)
        self.spinBox_dtw_window_size.setObjectName("spinBox_dtw_window_size")
        self.checkBox_dtw_normalize_vectors = QtWidgets.QCheckBox(parent=self.groupBox_dtw_method)
        self.checkBox_dtw_normalize_vectors.setGeometry(QtCore.QRect(240, 200, 151, 31))
        self.checkBox_dtw_normalize_vectors.setObjectName("checkBox_dtw_normalize_vectors")
        # self.doubleSpinBox_dtw_threshold = QtWidgets.QDoubleSpinBox(parent=self.groupBox_dtw_method)
        # self.doubleSpinBox_dtw_threshold.setGeometry(QtCore.QRect(230, 70, 171, 31))
        # self.doubleSpinBox_dtw_threshold.setDecimals(3)
        # self.doubleSpinBox_dtw_threshold.setMaximum(1.0)
        # self.doubleSpinBox_dtw_threshold.setObjectName("doubleSpinBox_dtw_threshold")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_dtw_method)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 201, 31))
        self.label_6.setObjectName("label_6")
        self.comboBox_dtw_distance = QtWidgets.QComboBox(parent=self.groupBox_dtw_method)
        self.comboBox_dtw_distance.setGeometry(QtCore.QRect(230, 30, 171, 22))
        self.comboBox_dtw_distance.setObjectName("comboBox_dtw_distance")
        self.comboBox_dtw_distance.addItem("")
        self.comboBox_dtw_distance.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_dtw_method)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 201, 41))
        self.label_5.setObjectName("label_5")
        self.groupBox_movement_vectors_sim = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_movement_vectors_sim.setGeometry(QtCore.QRect(10, 30, 421, 151))
        self.groupBox_movement_vectors_sim.setCheckable(True)
        self.groupBox_movement_vectors_sim.setChecked(True)
        self.groupBox_movement_vectors_sim.setObjectName("groupBox_movement_vectors_sim")
        self.checkBox_mov_vec_normalize = QtWidgets.QCheckBox(parent=self.groupBox_movement_vectors_sim)
        self.checkBox_mov_vec_normalize.setGeometry(QtCore.QRect(240, 120, 151, 20))
        self.checkBox_mov_vec_normalize.setObjectName("checkBox_mov_vec_normalize")
        self.doubleSpinBox_mov_vec_threshold = QtWidgets.QDoubleSpinBox(parent=self.groupBox_movement_vectors_sim)
        self.doubleSpinBox_mov_vec_threshold.setGeometry(QtCore.QRect(220, 71, 181, 31))
        self.doubleSpinBox_mov_vec_threshold.setDecimals(3)
        self.doubleSpinBox_mov_vec_threshold.setMaximum(1.0)
        self.doubleSpinBox_mov_vec_threshold.setObjectName("doubleSpinBox_mov_vec_threshold")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_movement_vectors_sim)
        self.label_3.setGeometry(QtCore.QRect(10, 75, 241, 21))
        self.label_3.setObjectName("label_3")
        self.checkBox_mov_vectors_distance_2 = QtWidgets.QComboBox(parent=self.groupBox_movement_vectors_sim)
        self.checkBox_mov_vectors_distance_2.setGeometry(QtCore.QRect(220, 30, 181, 22))
        self.checkBox_mov_vectors_distance_2.setObjectName("checkBox_mov_vectors_distance_2")
        self.checkBox_mov_vectors_distance_2.addItem("")
        self.checkBox_mov_vectors_distance_2.addItem("")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_movement_vectors_sim)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 211, 41))
        self.label_4.setObjectName("label_4")
        self.groupBox_smith_waterman = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_smith_waterman.setGeometry(QtCore.QRect(10, 450, 421, 241))
        self.groupBox_smith_waterman.setCheckable(True)
        self.groupBox_smith_waterman.setChecked(True)
        self.groupBox_smith_waterman.setObjectName("groupBox_smith_waterman")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_smith_waterman)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 201, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_smith_waterman)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 231, 61))
        self.label_8.setObjectName("label_8")
        self.comboBox_smithWm_distance = QtWidgets.QComboBox(parent=self.groupBox_smith_waterman)
        self.comboBox_smithWm_distance.setGeometry(QtCore.QRect(230, 30, 171, 22))
        self.comboBox_smithWm_distance.setObjectName("comboBox_smithWm_distance")
        self.comboBox_smithWm_distance.addItem("")
        self.comboBox_smithWm_distance.addItem("")
        self.doubleSpinBox_smithWm_threshold = QtWidgets.QDoubleSpinBox(parent=self.groupBox_smith_waterman)
        self.doubleSpinBox_smithWm_threshold.setGeometry(QtCore.QRect(230, 70, 171, 31))
        self.doubleSpinBox_smithWm_threshold.setDecimals(3)
        self.doubleSpinBox_smithWm_threshold.setMaximum(1.0)
        self.doubleSpinBox_smithWm_threshold.setObjectName("doubleSpinBox_smithWm_threshold")
        self.checkBox_smithWm_normalize_vectors = QtWidgets.QCheckBox(parent=self.groupBox_smith_waterman)
        self.checkBox_smithWm_normalize_vectors.setGeometry(QtCore.QRect(240, 200, 161, 31))
        self.checkBox_smithWm_normalize_vectors.setObjectName("checkBox_smithWm_normalize_vectors")
        self.doubleSpinBox_smithWm_Match_s = QtWidgets.QDoubleSpinBox(parent=self.groupBox_smith_waterman)
        self.doubleSpinBox_smithWm_Match_s.setGeometry(QtCore.QRect(140, 120, 71, 31))
        self.doubleSpinBox_smithWm_Match_s.setDecimals(1)
        self.doubleSpinBox_smithWm_Match_s.setMaximum(10.0)
        self.doubleSpinBox_smithWm_Match_s.setObjectName("doubleSpinBox_smithWm_Match_s")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_smith_waterman)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 101, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_smith_waterman)
        self.label_10.setGeometry(QtCore.QRect(10, 210, 111, 16))
        self.label_10.setObjectName("label_10")
        self.doubleSpinBox_smithWm_M_penalty = QtWidgets.QDoubleSpinBox(parent=self.groupBox_smith_waterman)
        self.doubleSpinBox_smithWm_M_penalty.setGeometry(QtCore.QRect(140, 201, 71, 31))
        self.doubleSpinBox_smithWm_M_penalty.setDecimals(1)
        self.doubleSpinBox_smithWm_M_penalty.setMaximum(10.0)
        self.doubleSpinBox_smithWm_M_penalty.setObjectName("doubleSpinBox_smithWm_M_penalty")
        self.doubleSpinBox_smithWm_G_penalty = QtWidgets.QDoubleSpinBox(parent=self.groupBox_smith_waterman)
        self.doubleSpinBox_smithWm_G_penalty.setGeometry(QtCore.QRect(140, 161, 71, 31))
        self.doubleSpinBox_smithWm_G_penalty.setDecimals(1)
        self.doubleSpinBox_smithWm_G_penalty.setMaximum(10.0)
        self.doubleSpinBox_smithWm_G_penalty.setObjectName("doubleSpinBox_smithWm_G_penalty")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_smith_waterman)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 91, 31))
        self.label_11.setObjectName("label_11")
        self.label_for_warnings = QtWidgets.QLabel(parent=self.groupBox)
        self.label_for_warnings.setGeometry(QtCore.QRect(380, 520, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.label_for_warnings.setFont(font)
        self.label_for_warnings.setText("")
        self.label_for_warnings.setObjectName("label_for_warnings")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(30, 746, 741, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 20, 331, 491))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_BodyPartAnalysis = QtWidgets.QGroupBox(parent=self.groupBox_5)
        self.groupBox_BodyPartAnalysis.setGeometry(QtCore.QRect(20, 70, 291, 411))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_BodyPartAnalysis.setFont(font)
        self.groupBox_BodyPartAnalysis.setCheckable(True)
        self.groupBox_BodyPartAnalysis.setChecked(False)
        self.groupBox_BodyPartAnalysis.setObjectName("groupBox_BodyPartAnalysis")
        self.cb_torso_top = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_torso_top.setGeometry(QtCore.QRect(20, 40, 101, 20))
        self.cb_torso_top.setObjectName("cb_torso_top")
        self.cb_torso_l = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_torso_l.setGeometry(QtCore.QRect(20, 70, 141, 20))
        self.cb_torso_l.setObjectName("cb_torso_l")
        self.cb_torso_r = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_torso_r.setGeometry(QtCore.QRect(20, 100, 181, 20))
        self.cb_torso_r.setObjectName("cb_torso_r")
        self.cb_torso_bottom = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_torso_bottom.setGeometry(QtCore.QRect(20, 130, 201, 20))
        self.cb_torso_bottom.setObjectName("cb_torso_bottom")
        self.cb_arm_l = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_arm_l.setGeometry(QtCore.QRect(20, 160, 89, 20))
        self.cb_arm_l.setObjectName("cb_arm_l")
        self.cb_arm_r = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_arm_r.setGeometry(QtCore.QRect(20, 190, 161, 20))
        self.cb_arm_r.setObjectName("cb_arm_r")
        self.cb_forearm_l = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_forearm_l.setGeometry(QtCore.QRect(20, 220, 141, 20))
        self.cb_forearm_l.setObjectName("cb_forearm_l")
        self.cb_forearm_r = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_forearm_r.setGeometry(QtCore.QRect(20, 250, 151, 20))
        self.cb_forearm_r.setObjectName("cb_forearm_r")
        self.cb_upper_leg_l = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_upper_leg_l.setGeometry(QtCore.QRect(20, 280, 171, 20))
        self.cb_upper_leg_l.setObjectName("cb_upper_leg_l")
        self.cb_upper_leg_r = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_upper_leg_r.setGeometry(QtCore.QRect(20, 310, 141, 20))
        self.cb_upper_leg_r.setObjectName("cb_upper_leg_r")
        self.cb_lower_leg_l = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_lower_leg_l.setGeometry(QtCore.QRect(20, 340, 151, 20))
        self.cb_lower_leg_l.setObjectName("cb_lower_leg_l")
        self.cb_lower_leg_r = QtWidgets.QCheckBox(parent=self.groupBox_BodyPartAnalysis)
        self.cb_lower_leg_r.setGeometry(QtCore.QRect(20, 370, 151, 20))
        self.cb_lower_leg_r.setObjectName("cb_lower_leg_r")
        self.checkBox_FullBodyAnalysis = QtWidgets.QCheckBox(parent=self.groupBox_5)
        self.checkBox_FullBodyAnalysis.setGeometry(QtCore.QRect(30, 20, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_FullBodyAnalysis.setFont(font)
        self.checkBox_FullBodyAnalysis.setChecked(True)
        self.checkBox_FullBodyAnalysis.setObjectName("checkBox_FullBodyAnalysis")
        self.line_3 = QtWidgets.QFrame(parent=self.groupBox_5)
        self.line_3.setGeometry(QtCore.QRect(30, 50, 241, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox_2.setGeometry(QtCore.QRect(500, 670, 231, 61))
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.groupBox_tlcc_method = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_tlcc_method.setGeometry(QtCore.QRect(480, 520, 331, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_tlcc_method.setFont(font)
        self.groupBox_tlcc_method.setCheckable(True)
        self.groupBox_tlcc_method.setObjectName("groupBox_tlcc_method")
        self.checkBox_smithWm_normalize_vectors_2 = QtWidgets.QCheckBox(parent=self.groupBox_tlcc_method)
        self.checkBox_smithWm_normalize_vectors_2.setGeometry(QtCore.QRect(10, 70, 211, 41))
        self.checkBox_smithWm_normalize_vectors_2.setObjectName("checkBox_smithWm_normalize_vectors_2")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_tlcc_method)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 161, 31))
        self.label_12.setObjectName("label_12")
        self.spinBox_tlcc_max_leg = QtWidgets.QSpinBox(parent=self.groupBox_tlcc_method)
        self.spinBox_tlcc_max_leg.setGeometry(QtCore.QRect(210, 50, 71, 21))
        self.spinBox_tlcc_max_leg.setMinimum(1)
        self.spinBox_tlcc_max_leg.setMaximum(10)
        self.spinBox_tlcc_max_leg.setObjectName("spinBox_tlcc_max_lag")

        # setting pre-defiend values
        self.doubleSpinBox_mov_vec_threshold.setValue(0.02)
        self.spinBox_dtw_radius.setValue(5)
        self.doubleSpinBox_smithWm_threshold.setValue(0.03)
        self.doubleSpinBox_smithWm_Match_s.setValue(4.0)
        self.doubleSpinBox_smithWm_M_penalty.setValue(1.0)
        self.doubleSpinBox_smithWm_G_penalty.setValue(0.5)
        self.spinBox_tlcc_max_leg.setValue(10)

        # Warning label for error messages
        self.label_for_warnings = QtWidgets.QLabel(parent=Dialog)
        self.label_for_warnings.setGeometry(QtCore.QRect(400, 540, 251, 20))
        self.label_for_warnings.setStyleSheet("background-color: transparent; color: red;")
        self.label_for_warnings.setObjectName("label_for_warnings")

        # Call the method to set the exclusive behavior
        self.set_exclusive_behavior()

        self.retranslateUi(Dialog)

        # Connect OK button to a custom method for validation
        self.buttonBox_2.accepted.connect(lambda: self.validate_inputs(Dialog))  # type: ignore
        self.buttonBox_2.rejected.connect(Dialog.reject)  # type: ignore

        QtCore.QMetaObject.connectSlotsByName(Dialog)
        # Apply enhanced dark mode stylesheet


    def set_exclusive_behavior(self):
        # Disable Body Parts Group when Full Body is checked, and vice versa
        self.checkBox_FullBodyAnalysis.toggled.connect(self.toggle_body_part_analysis)
        self.groupBox_BodyPartAnalysis.toggled.connect(self.toggle_full_body_analysis)

    def show_warning(self, message, duration=30000):
        """
        Display a warning message on label_for_warnings.
        The message will disappear after the specified duration (in milliseconds).
        """
        self.label_for_warnings.setText(message)

        # Clear the warning message after the specified duration
        QtCore.QTimer.singleShot(duration, self.clear_warning)

    def clear_warning(self):
        """Clear the warning message."""
        self.label_for_warnings.setText("")
    def toggle_body_part_analysis(self, checked):
        """Disable body parts when Full Body is checked."""
        self.groupBox_BodyPartAnalysis.setChecked(not checked)
        for child in self.groupBox_BodyPartAnalysis.children():
            if isinstance(child, QtWidgets.QCheckBox):
                child.setEnabled(not checked)  # Disable/Enable all checkboxes for body parts

    def toggle_full_body_analysis(self, checked):
        """Disable Full Body when Body Parts is checked."""
        self.checkBox_FullBodyAnalysis.setChecked(not checked)

    def validate_inputs(self, Dialog):

        if self.groupBox_BodyPartAnalysis.isChecked():
            if not any([
                self.cb_torso_top.isChecked(), self.cb_torso_l.isChecked(), self.cb_torso_r.isChecked(),
                self.cb_torso_bottom.isChecked(), self.cb_arm_l.isChecked(), self.cb_arm_r.isChecked(),
                self.cb_forearm_l.isChecked(), self.cb_forearm_r.isChecked(), self.cb_upper_leg_l.isChecked(),
                self.cb_upper_leg_r.isChecked(), self.cb_lower_leg_l.isChecked(), self.cb_lower_leg_r.isChecked()
            ]):
                self.show_warning("Please select at least one body part.")
                return  # Stop here to prevent the dialog from closing
        # Validate that at least one analysis method is selected
        if not any([
            self.groupBox_movement_vectors_sim.isChecked(),
            self.groupBox_smith_waterman.isChecked(),
            self.groupBox_dtw_method.isChecked(),
            self.groupBox_tlcc_method.isChecked()
        ]):
            self.show_warning("Please select at least one analysis method.")
            return  # Stop here to prevent the dialog from closing

        Dialog.accept()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Synchrony analysis settings"))
        self.groupBox.setTitle(_translate("Dialog", "Analysis Method"))
        self.groupBox_dtw_method.setTitle(_translate("Dialog", "Dynamic time warping (DTW)"))
        self.label.setText(_translate("Dialog", "FastDTW Radius"))
        self.checkBox_dtw_vec_smoothing.setText(_translate("Dialog", "Apply vector smoothing"))
        self.label_2.setText(_translate("Dialog", "Smoothing window size :"))
        self.checkBox_dtw_normalize_vectors.setText(_translate("Dialog", "Normalize vectors"))
        # self.label_6.setText(_translate("Dialog", "Threshold alignment value"))
        self.comboBox_dtw_distance.setItemText(0, _translate("Dialog", "Euclidean distance"))
        self.comboBox_dtw_distance.setItemText(1, _translate("Dialog", "Cosine similarity"))
        self.label_5.setText(_translate("Dialog", "Measure alignment based on:"))
        self.groupBox_movement_vectors_sim.setTitle(_translate("Dialog", "Movement vectors similarity analysis"))
        self.checkBox_mov_vec_normalize.setText(_translate("Dialog", "Normalize vectors"))
        self.label_3.setText(_translate("Dialog", "Threshold alignment value"))
        self.checkBox_mov_vectors_distance_2.setItemText(0, _translate("Dialog", "Euclidean distance"))
        self.checkBox_mov_vectors_distance_2.setItemText(1, _translate("Dialog", "Cosine similarity"))
        self.label_4.setText(_translate("Dialog", "Measure alignment based on:"))
        self.groupBox_smith_waterman.setTitle(_translate("Dialog", "Smith-Waterman adapted"))
        self.label_7.setText(_translate("Dialog", "Measure alignment based on:"))
        self.label_8.setText(_translate("Dialog", "Threshold alignment value"))
        self.comboBox_smithWm_distance.setItemText(0, _translate("Dialog", "Euclidean distance"))
        self.comboBox_smithWm_distance.setItemText(1, _translate("Dialog", "Cosine similarity"))
        self.checkBox_smithWm_normalize_vectors.setText(_translate("Dialog", "Normalize vectors"))
        self.label_9.setText(_translate("Dialog", "Match score:"))
        self.label_10.setText(_translate("Dialog", "Mismatch penalty:"))
        self.label_11.setText(_translate("Dialog", "Gap penalty:"))
        self.groupBox_BodyPartAnalysis.setTitle(_translate("Dialog", "Body Parts Analysis"))
        self.cb_torso_top.setText(_translate("Dialog", "TORSO_TOP"))
        self.cb_torso_l.setText(_translate("Dialog", "TORSO_LEFT"))
        self.cb_torso_r.setText(_translate("Dialog", "TORSO_RIGHT"))
        self.cb_torso_bottom.setText(_translate("Dialog", "TORSO_BOTTOM"))
        self.cb_arm_l.setText(_translate("Dialog", "ARM_LEFT"))
        self.cb_arm_r.setText(_translate("Dialog", "ARM_RIGHT"))
        self.cb_forearm_l.setText(_translate("Dialog", "FOREARM_LEFT"))
        self.cb_forearm_r.setText(_translate("Dialog", "FOREARM_RIGHT"))
        self.cb_upper_leg_l.setText(_translate("Dialog", "UPPER_LEG_LEFT"))
        self.cb_upper_leg_r.setText(_translate("Dialog", "UPPER_LEG_RIGHT"))
        self.cb_lower_leg_l.setText(_translate("Dialog", "LOWER_LEG_LEFT"))
        self.cb_lower_leg_r.setText(_translate("Dialog", "LOWER_LEG_RIGHT"))
        self.checkBox_FullBodyAnalysis.setText(_translate("Dialog", "Full Body Analysis"))
        self.groupBox_tlcc_method.setTitle(_translate("Dialog", " Time lagged cross correlations (TLCC)"))
        self.checkBox_smithWm_normalize_vectors_2.setText(_translate("Dialog", "Normalize vectors"))
        self.label_12.setText(_translate("Dialog", "Max lag:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = SynchronyAnalysisDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())